"""empty message

Revision ID: 36f421fbb7d4
Revises: 447c7002fe46
Create Date: 2024-05-31 22:55:10.007353

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "36f421fbb7d4"
down_revision = "447c7002fe46"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
