"""empty message

Revision ID: 0223aeb1502f
Revises: 50352df428b8
Create Date: 2024-06-01 06:04:50.355728

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0223aeb1502f"
down_revision = "50352df428b8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
