"""empty message

Revision ID: c9bd6a93914c
Revises: f8fe8f2e7cb5
Create Date: 2024-05-31 21:16:36.422820

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c9bd6a93914c"
down_revision = "f8fe8f2e7cb5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("file_size", sa.Double(), nullable=True),
        sa.Column("file_type", sa.String(), nullable=True),
        sa.Column("file_name", sa.String(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_files_date"), "files", ["date"], unique=False)
    op.create_index(op.f("ix_files_file_name"), "files", ["file_name"], unique=False)
    op.create_index(op.f("ix_files_file_size"), "files", ["file_size"], unique=False)
    op.create_index(op.f("ix_files_file_type"), "files", ["file_type"], unique=False)
    op.create_index(op.f("ix_files_id"), "files", ["id"], unique=False)
    op.create_index(op.f("ix_files_user_id"), "files", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_files_user_id"), table_name="files")
    op.drop_index(op.f("ix_files_id"), table_name="files")
    op.drop_index(op.f("ix_files_file_type"), table_name="files")
    op.drop_index(op.f("ix_files_file_size"), table_name="files")
    op.drop_index(op.f("ix_files_file_name"), table_name="files")
    op.drop_index(op.f("ix_files_date"), table_name="files")
    op.drop_table("files")
    # ### end Alembic commands ###
