"""empty message

Revision ID: 665faf33f8d7
Revises: c9bd6a93914c
Create Date: 2024-05-31 21:16:50.274240

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "665faf33f8d7"
down_revision = "c9bd6a93914c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
