"""empty message

Revision ID: c61db39c6ba6
Revises: 0223aeb1502f
Create Date: 2024-06-01 11:47:05.921222

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c61db39c6ba6"
down_revision = "0223aeb1502f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
