"""empty message

Revision ID: 235073b04dbe
Revises: c6ac5863387d
Create Date: 2024-05-31 08:31:56.259158

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "235073b04dbe"
down_revision = "c6ac5863387d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
