"""empty message

Revision ID: 4ecac35faaf0
Revises: 98b854262390
Create Date: 2024-05-31 03:21:38.782342

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4ecac35faaf0"
down_revision = "98b854262390"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
