"""empty message

Revision ID: 36c702835947
Revises: 4903ac53488b
Create Date: 2024-05-31 20:05:47.812704

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "36c702835947"
down_revision = "4903ac53488b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
