"""empty message

Revision ID: 7b2155f61ab3
Revises: 2a9b81ea56e1
Create Date: 2024-06-01 01:36:19.533865

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7b2155f61ab3"
down_revision = "2a9b81ea56e1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
