"""empty message

Revision ID: 50352df428b8
Revises: 7b2155f61ab3
Create Date: 2024-06-01 06:04:23.738809

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "50352df428b8"
down_revision = "7b2155f61ab3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("files", sa.Column("file_path", sa.String(), nullable=True))
    op.create_index(op.f("ix_files_file_path"), "files", ["file_path"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_files_file_path"), table_name="files")
    op.drop_column("files", "file_path")
    # ### end Alembic commands ###
