"""empty message

Revision ID: 4d0356eb5009
Revises: c61db39c6ba6
Create Date: 2024-06-01 11:47:44.697128

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4d0356eb5009"
down_revision = "c61db39c6ba6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
