"""empty message

Revision ID: c6ac5863387d
Revises: eb51876bba29
Create Date: 2024-05-31 06:45:52.955418

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c6ac5863387d"
down_revision = "eb51876bba29"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
