"""empty message

Revision ID: 7c13ce32f206
Revises: 46c2c92b2db7
Create Date: 2024-05-31 16:59:55.497426

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7c13ce32f206"
down_revision = "46c2c92b2db7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
