"""empty message

Revision ID: cfe4cbcf1451
Revises: ea5b8a9d3016
Create Date: 2024-06-01 01:31:25.131825

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cfe4cbcf1451"
down_revision = "ea5b8a9d3016"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
