"""empty message

Revision ID: 26e66d9988b6
Revises: 819cbf6e030b
Create Date: 2024-06-01 01:08:04.424472

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "26e66d9988b6"
down_revision = "819cbf6e030b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("file_size", sa.Double(), nullable=True),
        sa.Column("file_type", sa.String(), nullable=True),
        sa.Column("file_name", sa.String(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_files_date"), "files", ["date"], unique=False)
    op.create_index(op.f("ix_files_file_name"), "files", ["file_name"], unique=False)
    op.create_index(op.f("ix_files_file_size"), "files", ["file_size"], unique=False)
    op.create_index(op.f("ix_files_file_type"), "files", ["file_type"], unique=False)
    op.create_index(op.f("ix_files_id"), "files", ["id"], unique=False)
    op.create_index(op.f("ix_files_user_id"), "files", ["user_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.Column("file_type", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("can_delete", sa.Boolean(), nullable=True),
        sa.Column("jpg_quality", sa.Integer(), nullable=True),
        sa.Column("crypt_file", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_hashed_password"), "users", ["hashed_password"], unique=False
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_hashed_password"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_files_user_id"), table_name="files")
    op.drop_index(op.f("ix_files_id"), table_name="files")
    op.drop_index(op.f("ix_files_file_type"), table_name="files")
    op.drop_index(op.f("ix_files_file_size"), table_name="files")
    op.drop_index(op.f("ix_files_file_name"), table_name="files")
    op.drop_index(op.f("ix_files_date"), table_name="files")
    op.drop_table("files")
    # ### end Alembic commands ###
