"""empty message

Revision ID: c8ebc5b4d1a4
Revises: 26e66d9988b6
Create Date: 2024-06-01 01:08:17.179511

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c8ebc5b4d1a4"
down_revision = "26e66d9988b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
