"""empty message

Revision ID: f8fe8f2e7cb5
Revises: 785a725d945a
Create Date: 2024-05-31 20:12:04.442470

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f8fe8f2e7cb5"
down_revision = "785a725d945a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
