"""empty message

Revision ID: 785a725d945a
Revises: 36c702835947
Create Date: 2024-05-31 20:11:24.558179

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "785a725d945a"
down_revision = "36c702835947"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "file_type",
        existing_type=postgresql.ARRAY(sa.INTEGER()),
        type_=sa.ARRAY(sa.String()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "file_type",
        existing_type=sa.ARRAY(sa.String()),
        type_=postgresql.ARRAY(sa.INTEGER()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
