"""empty message

Revision ID: 4903ac53488b
Revises: 7c13ce32f206
Create Date: 2024-05-31 19:58:37.934132

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4903ac53488b"
down_revision = "7c13ce32f206"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("file_type", sa.ARRAY(sa.Integer()), nullable=True)
    )
    op.add_column("users", sa.Column("file_size", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("can_delete", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("jpg_quality", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("hash_file", sa.Boolean(), nullable=True))
    op.create_index(
        op.f("ix_users_hashed_password"), "users", ["hashed_password"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_hashed_password"), table_name="users")
    op.drop_column("users", "hash_file")
    op.drop_column("users", "jpg_quality")
    op.drop_column("users", "can_delete")
    op.drop_column("users", "file_size")
    op.drop_column("users", "file_type")
    # ### end Alembic commands ###
