"""empty message

Revision ID: ea5b8a9d3016
Revises: c8ebc5b4d1a4
Create Date: 2024-06-01 01:31:14.165828

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ea5b8a9d3016"
down_revision = "c8ebc5b4d1a4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
